package com.centurylink.dsp.valueobjects.impl;

public class Field {
	
	private String name;
	private String type;
	private String alias;
	private Object value;
	private boolean changed;
	private boolean changeable;
	private boolean autoGenerated;
	
	public final static String TYPE_VARCHAR = "STRING";
	public final static String TYPE_NUMERIC = "NUMERIC";
	public final static String TYPE_DATE = "DATE";
	public final static String TYPE_CHAR = "CHAR";
	public final static String TYPE_CONCAT = "CONCAT";
	public final static String TYPE_CLOB = "CLOB";
	public final static String TYPE_FLOAT = "FLOAT";
	
	public Field (String name, String type)
	{
		this.name = name;
		this.type = type;
		this.alias = name;
		this.changed = false;
		this.changeable = true;
		this.autoGenerated = false;
	}
	
	public Field (String name, String type, String alias)
	{
		this(name, type);
		this.alias = alias;
	}

	public Field (String name, String type, boolean changeable)
	{
		this(name, type);
		this.changeable = changeable;
	}

	public String getName() {
		return name;
	}

	public String getType() {
		return type;
	}

	public String getAlias() {
		return alias;
	}
	
	public void setValue (Object value)
	{
		this.value = value;
		this.changed = true;
	}

	/*
	 * For normal columns just set the value, will be overridden in Reference type Fields 
	 * to handle the specific logic
	 */
	public void setValueByRef (Object value)
	{
		setValue(value);
	}
	
	public Object getValue()
	{
		return this.value;
	}
	
	public String getValueAsString()
	{
		if (this.value != null)
			return this.value.toString();
		else
			return null;
	}
	
	public String getQueryValue()
	{
		if (this.value != null)
			return "'" + this.value.toString() + "'";
		else 
			return "NULL";
	}
	
	public String getInsertValue()
	{
		return getQueryValue();
	}
	
	public boolean hasChanged()
	{
		return this.changed;
	}
	
	public void setChanged(boolean changed)
	{
		this.changed = changed;
	}
	
	public boolean isChangeable()
	{
		return this.changeable;
	}

	public boolean isAutoGenerated()
	{
		return this.autoGenerated;
	}
	
	protected void setAutoGenerated(boolean autoGenerated)
	{
		this.autoGenerated = autoGenerated;
	}

	@Override
	public String toString() {
		return "Field [name=" + name + ", type=" + type + ", alias=" + alias
				+ ", value=" + getValueAsString() + "]";
	}

}
