package com.centurylink.dsp.valueobjects.impl;

import com.centurylink.dsp.valueobjects.dataaccess.ValueObjectDataAccessUtil;
import com.centurylink.dsp.valueobjects.dataaccess.ValueObjectDataAccessUtilFactory;

public class MaxSequenceField extends Field{
	
	private ValueObjectDataAccessUtil valueObjectDataAccessUtil;
	
	private String maxSeqTableName;

	public MaxSequenceField (String name, String maxSeqTableName)
	{
		super(name, "NUMERIC", false);
		
		valueObjectDataAccessUtil = ValueObjectDataAccessUtilFactory.getValueObjectDataAccessUtil("com.centurylink.icl.clcnew");

		this.maxSeqTableName = maxSeqTableName;
		
		setAutoGenerated(true);
	}
	
	public String getMaxSeqTableName() 
	{
		return this.maxSeqTableName;
	}
	
	@Override
	public String getInsertValue()
	{
		long longSeq = valueObjectDataAccessUtil.getMaxSeq(this);
		this.setValue(String.valueOf(longSeq));
		return String.valueOf(longSeq);
	}

	
}
