package com.centurylink.dsp.valueobjects.impl;

import com.centurylink.dsp.valueobjects.dataaccess.ValueObjectDataAccessUtil;
import com.centurylink.dsp.valueobjects.dataaccess.ValueObjectDataAccessUtilFactory;

public class SequenceField extends Field {
	
	private String seqTableName = "";
	
	private ValueObjectDataAccessUtil valueObjectDataAccessUtil;
	
	public SequenceField (String name, String seqTableName)
	{
		super(name, "NUMERIC", false);
		this.seqTableName = seqTableName;
		
		valueObjectDataAccessUtil = ValueObjectDataAccessUtilFactory.getValueObjectDataAccessUtil("com.centurylink.icl.clcnew");

		setAutoGenerated(true);
	}
	
	public String getSeqTableName()
	{
		return this.seqTableName;
	}

	@Override
	public String getInsertValue()
	{
		long longSeq = valueObjectDataAccessUtil.getNextSeq(this);
		this.setValue(String.valueOf(longSeq));
		return String.valueOf(longSeq);
	}
}
