package com.centurylink.dsp.valueobjects.impl;


public class SystemDateField extends DateField {
	
	public SystemDateField (String name)
	{
		this(name, true);
	}
	
	public SystemDateField (String name, boolean changeable)
	{
		super(name, changeable);
		setAutoGenerated(true);
	}
	
	@Override
	public String getInsertValue()
	{
		return "SYSDATE";
	}

}
